#ifndef DEVAULT_H
#define DEVAULT_H

#include <stddef.h>

#define MAX_NAME_LEN 64
#define MAX_PATH_LEN 512
#define MAX_URL_LEN 512
#define MAX_RECORDS 1000
#define MAX_TAGS 100

#define SEPARATOR_LEN 48

typedef enum {
	ERR_NONE = 0,
	ERR_EMPTY_INPUT,
	ERR_EXCEEDS_MAX_LEN,
	ERR_MALFORMED_URL,
	ERR_INVALID_SCHEME,
	ERR_INVALID_CHARS,
	ERR_PATH_TRAVERSAL,
	ERR_OPTION_NOT_NUMERIC,
	ERR_OPTION_OUT_OF_RANGE,
	ERR_NAME_STARTS_WITH_DIGIT,
	ERR_RESERVED_FILENAME,
	ERR_RECORD_NOT_FOUND,
	ERR_TAG_NOT_FOUND,
	ERR_TAG_ID_NOT_FOUND,
	ERR_RECORD_CREATE_FAILED,
	ERR_TAG_CREATE_FAILED,
	ERR_NO_TAGS_IN_RECORD,
	ERR_EMPTY_TAG_LIST,
	ERR_EMPTY_RECORD_LIST,
	ERR_RECORD_SEARCH_NO_MATCH,
	ERR_INTERNAL
} dv_error;

typedef enum {
	TYPE_URL,
	TYPE_PATH,
	TYPE_NAME,
	TYPE_OPTION,
	TYPE_ALPHANAME,
	TYPE_APP
} input_type;

typedef struct _dv_ctx dv_ctx_t;

dv_ctx_t *create_dv_ctx(void);

void destroy_dv_ctx(dv_ctx_t *ctx);

void dv_print_error(dv_ctx_t *ctx, input_type type);

#endif
